/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopp;
import javax.swing.JOptionPane;


/**
 *
 * @author jmcar
 */
public class panelRegular extends javax.swing.JFrame {

    /**
     * Creates new form panelRegular
     */
    public panelRegular() {
        initComponents();
    }
    int numero1 = 0;
    int numero2 = 0;

       
    String digito1 = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDivi = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        lblOperacion2 = new javax.swing.JLabel();
        btnResultado = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSuma.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnResta.setText("-");
        btnResta.setToolTipText("");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnDivi.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnDivi.setText("÷");
        btnDivi.setToolTipText("");
        btnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiviActionPerformed(evt);
            }
        });

        btnCE.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnMulti.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnMulti.setText("x");
        btnMulti.setToolTipText("");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        lblOperacion2.setBackground(new java.awt.Color(51, 51, 51));
        lblOperacion2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        lblOperacion2.setForeground(new java.awt.Color(102, 204, 0));

        btnResultado.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnResultado.setText("=");
        btnResultado.setToolTipText("");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblOperacion2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblOperacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        String numero = lblOperacion2.getText();
        if(numero1 == 0 && numero!="" && numero!=null) {
            numero1 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            digito1= "+";
            texto = texto + "+";
            lblOperacion2.setText(texto);
        }else if(numero2 != 0){
            JOptionPane.showMessageDialog(null,"Debe realizar una operacion a la vez");
        }else {
            String texto = lblOperacion2.getText();
            digito1= "+";
            texto = texto + "+";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        String numero = lblOperacion2.getText();
        if(numero1 == 0 && numero!="" && numero!=null) {
            numero1 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            digito1= "-";
            texto = texto + "-";
            lblOperacion2.setText(texto);
        }else if(numero2 != 0){
            JOptionPane.showMessageDialog(null,"Debe realizar una operacion a la vez");
        }else {
            String texto = lblOperacion2.getText();
            digito1= "-";
            texto = texto + "-";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiviActionPerformed
        // TODO add your handling code here:
        String numero = lblOperacion2.getText();
        if(numero1 == 0 && numero!="" && numero!=null) {
            numero1 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            digito1= "÷";
            texto = texto + "÷";
            lblOperacion2.setText(texto);
        }else if(numero2 != 0){
            JOptionPane.showMessageDialog(null,"Debe realizar una operacion a la vez");
        }else {
            String texto = lblOperacion2.getText();
            digito1= "÷";
            texto = texto + "÷";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btnDiviActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        lblOperacion2.setText("");
        numero1 = 0;
        numero2 = 0;

        digito1= "";
    }//GEN-LAST:event_btnCEActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:

        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "0";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "0";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "0";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn0ActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        // TODO add your handling code here:
        String numero = lblOperacion2.getText();
        if(numero1 == 0 && numero!="" && numero!=null) {
            numero1 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            digito1= "x";
            texto = texto + "x";
            lblOperacion2.setText(texto);
        }else if(numero2 != 0){
            JOptionPane.showMessageDialog(null,"Debe realizar una operacion a la vez");
        }else {
            String texto = lblOperacion2.getText();
            digito1= "x";
            texto = texto + "x";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed

        int resultado = 0;
        if(numero1 == 0 && numero2 == 0) {
            JOptionPane.showMessageDialog(null, "Debe digitar mas numeros");
        } else {
            switch(digito1){
                case "+":
                resultado = numero1 + numero2;
                lblOperacion2.setText("");
                lblOperacion2.setText(String.valueOf(resultado));

                numero1 = resultado;
                numero2 = 0;
                digito1 = "";
                break;
                case "-":
                resultado = numero1 - numero2;
                lblOperacion2.setText("");
                lblOperacion2.setText(String.valueOf(resultado));
                numero1 = resultado;
                numero2 = 0;
                digito1 = "";
                break;

                case "x":
                resultado = numero1 * numero2;
                lblOperacion2.setText("");
                lblOperacion2.setText(String.valueOf(resultado));
                numero1 = resultado;
                numero2 = 0;
                digito1 = "";
                break;

                case "÷":
                resultado = numero1 / numero2;
                lblOperacion2.setText("");
                lblOperacion2.setText(String.valueOf(resultado));
                numero1 = resultado;
                numero2 = 0;
                digito1 = "";
                break;

            }
        }

    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "2";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "2";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "2";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:

        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "3";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "3";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "3";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:

        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "4";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "4";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "4";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "5";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "5";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "5";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:

        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "6";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "6";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "6";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "1";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "1";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "1";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:

        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "8";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "8";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "8";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "9";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "9";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "9";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn9ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:

        String numero = String.valueOf(numero2);

        if(numero1== 0) {
            String texto = lblOperacion2.getText();
            texto = texto + "7";
            lblOperacion2.setText(texto);
        }else if(numero1 != 0) {
            numero = numero + "7";
            numero2 = Integer.parseInt(numero);
            String texto = lblOperacion2.getText();
            texto = texto + "7";
            lblOperacion2.setText(texto);
        }

    }//GEN-LAST:event_btn7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelRegular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDivi;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel lblOperacion2;
    // End of variables declaration//GEN-END:variables
}
