/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopp;

/**
 *
 * @author javi
 */
public class panelTiempo extends javax.swing.JFrame {

    /**
     * Creates new form panelTiempo
     */
    public panelTiempo() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        tfUnit2 = new javax.swing.JTextField();
        Box1 = new javax.swing.JComboBox<>();
        tfUnit1 = new javax.swing.JTextField();
        Box2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        tfUnit2.setEditable(false);
        tfUnit2.setBackground(new java.awt.Color(255, 255, 255));
        tfUnit2.setForeground(new java.awt.Color(0, 0, 0));

        Box1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milisegundo", "Segundo", "Minuto", "Hora", "Dia" }));

        tfUnit1.setBackground(new java.awt.Color(255, 255, 255));
        tfUnit1.setForeground(new java.awt.Color(0, 0, 0));

        Box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milisegundo", "Segundo", "Minuto", "Hora", "Dia" }));

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Convertir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Resultado:");

        jPanel8.setBackground(new java.awt.Color(0, 0, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Convertidor de Tiempo");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Box2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(tfUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton4))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Box2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String box1 = (String) Box1.getSelectedItem();
        String box2 = (String) Box2.getSelectedItem();

        try {

            if (box1.equals("Milisegundo") && box2.equals("Segundo")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double s = (double) (m / 1000);

                tfUnit2.setText(String.valueOf(s));
            } else if (box1.equals("Milisegundo") && box2.equals("Minuto")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double s = (double) (m / 60000);

                tfUnit2.setText(String.valueOf(s));
            } else if (box1.equals("Milisegundo") && box2.equals("Hora")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double s = (double) (m / 3600000);

                tfUnit2.setText(String.valueOf(s));
            } else if (box1.equals("Milisegundo") && box2.equals("Dia")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double s = (double) (m / 86400000);

                tfUnit2.setText(String.valueOf(s));
            } else if (box1.equals("Segundo") && box2.equals("Milisegundo")) {
                double s = Double.parseDouble(tfUnit1.getText());

                double m = (double) (s * 1000);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Segundo") && box2.equals("Minuto")) {
                double s = Double.parseDouble(tfUnit1.getText());

                double m = (double) (s / 60);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Segundo") && box2.equals("Hora")) {
                double s = Double.parseDouble(tfUnit1.getText());

                double m = (double) (s / 3600);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Segundo") && box2.equals("Dia")) {
                double s = Double.parseDouble(tfUnit1.getText());

                double m = (double) (s / 86400);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Minuto") && box2.equals("Milisegundo")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double mi = (double) (m * 60000);

                tfUnit2.setText(String.valueOf(mi));
            } else if (box1.equals("Minuto") && box2.equals("Segundo")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double mi = (double) (m * 60);

                tfUnit2.setText(String.valueOf(mi));
            } else if (box1.equals("Minuto") && box2.equals("Hora")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double mi = (double) (m / 60);

                tfUnit2.setText(String.valueOf(mi));
            } else if (box1.equals("Minuto") && box2.equals("Dia")) {
                double m = Double.parseDouble(tfUnit1.getText());

                double mi = (double) (m / 1440);

                tfUnit2.setText(String.valueOf(mi));
            } else if (box1.equals("Hora") && box2.equals("Milisegundo")) {
                double h = Double.parseDouble(tfUnit1.getText());

                double m = (double) (h * 3600000);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Hora") && box2.equals("Segundo")) {
                double h = Double.parseDouble(tfUnit1.getText());

                double m = (double) (h * 3600);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Hora") && box2.equals("Minuto")) {
                double h = Double.parseDouble(tfUnit1.getText());

                double m = (double) (h * 60);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Hora") && box2.equals("Dia")) {
                double h = Double.parseDouble(tfUnit1.getText());

                double m = (double) (h / 24);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Dia") && box2.equals("Milisegundo")) {
                double d = Double.parseDouble(tfUnit1.getText());

                double m = (double) (d * 86400000);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Dia") && box2.equals("Segundo")) {
                double d = Double.parseDouble(tfUnit1.getText());

                double m = (double) (d * 86400);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Dia") && box2.equals("Minuto")) {
                double d = Double.parseDouble(tfUnit1.getText());

                double m = (double) (d * 1440);

                tfUnit2.setText(String.valueOf(m));
            } else if (box1.equals("Dia") && box2.equals("Hora")) {
                double d = Double.parseDouble(tfUnit1.getText());

                double m = (double) (d * 24);

                tfUnit2.setText(String.valueOf(m));
            } else {
                double u = Double.parseDouble(tfUnit1.getText());

                tfUnit2.setText(String.valueOf(u));

            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tfUnit1.setText("");
        tfUnit2.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelTiempo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box1;
    private javax.swing.JComboBox<String> Box2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField tfUnit1;
    private javax.swing.JTextField tfUnit2;
    // End of variables declaration//GEN-END:variables
}
